export const FORMULAS = [
  {
    id: 'worst-case',
    name: '极值法（最坏情况）',
    formula: 'T = T₁ + T₂ + T₃ + …',
    latex: 'T = T_1 + T_2 + T_3 + \\cdots',
    desc: '各组成环公差代数相加，结果最保守，适用于 100% 安全要求。',
    tags: ['极值', '公差', '尺寸链'],
    category: '尺寸链',
  },
  {
    id: 'rss',
    name: 'RSS 法（概率法）',
    formula: 'T = √(T₁² + T₂² + T₃² + …)',
    latex: 'T = \\sqrt{T_1^2 + T_2^2 + T_3^2 + \\cdots}',
    desc: '独立变量假设下的统计叠加，一般对应约 95% 合格率。',
    tags: ['RSS', '概率', '公差'],
    category: '尺寸链',
  },
  {
    id: 'modified-rss',
    name: '修正 RSS 法',
    formula: 'T_mod = k × √(T₁² + T₂² + …)',
    latex: 'T_{mod} = k \\cdot \\sqrt{T_1^2 + T_2^2 + \\cdots}',
    desc: '在 RSS 基础上乘以分布修正系数 $k$，适用于均匀/偏态等非正态场景。',
    tags: ['RSS', '修正', '偏态'],
    category: '尺寸链',
  },
  {
    id: 'sigma6-rss',
    name: '6σ RSS 法',
    formula: 'T = 6√(Σ(Tᵢ/Kᵢ)²)',
    latex: 'T = 6\\sqrt{\\sum \\left(\\frac{T_i}{K_i}\\right)^2}',
    desc: '将各环公差按分布 $K$ 值换算为标准差后做 $6\\sigma$ 叠加，适用于统计公差设计。',
    tags: ['6σ', 'RSS', '统计'],
    category: '尺寸链',
  },
  {
    id: 'gdt-position',
    name: '2D 位置度合成',
    formula: 'T_pos ≈ 2√(RSS_x² + RSS_y²)',
    latex: 'T_{pos} \\approx 2\\sqrt{RSS_x^2 + RSS_y^2}',
    desc: '$X$/$Y$ 方向定位偏差分别 RSS 合成后，再换算为位置度公差带直径。',
    tags: ['GD&T', '位置度', '2D'],
    category: '尺寸链',
  },
  {
    id: 'alloc-equal-effect',
    name: '等贡献 RSS 分配',
    formula: 'Tᵢ = T·fᵢ / √(Σf²)',
    latex: 'T_i = T \\cdot \\frac{f_i}{\\sqrt{\\sum f_j^2}}',
    desc: '各组成环对 RSS 方差贡献相等时的公差分配，传递系数 $f$ 表示灵敏度。',
    tags: ['分配', 'RSS', '等贡献'],
    category: '尺寸链',
  },
  {
    id: 'alloc-min-cost',
    name: '最小成本 RSS 分配',
    formula: 'Tᵢ ∝ √(cᵢ)·fᵢ',
    latex: 'T_i \\propto \\sqrt{c_i} \\cdot f_i',
    desc: '在 RSS 约束下按成本系数 $c$ 优化分配，加工成本高的环分配更小公差。',
    tags: ['分配', '成本', 'RSS'],
    category: '尺寸链',
  },
  {
    id: 'weighted-rss',
    name: '加权 RSS',
    formula: 'T = √(Σ(T×f)²)',
    latex: 'T = \\sqrt{\\sum (T_i \\cdot f_i)^2}',
    desc: '传递系数加权的 RSS 叠加。',
    tags: ['RSS', '加权'],
    category: '尺寸链',
  },
  {
    id: 't-to-sigma',
    name: '公差 → 标准差',
    formula: 'σ = T / K',
    latex: '\\sigma = \\frac{T}{K}',
    desc: '$K$ 为分布系数：正态 6.0，均匀 3.46，三角 4.24，偏态 5.0。',
    tags: ['转换', '正态', '标准差'],
    category: '统计',
  },
  {
    id: 'sigma-to-t',
    name: '标准差 → 公差',
    formula: 'T = σ × K',
    latex: 'T = \\sigma \cdot K',
    desc: '由过程标准差 $\\sigma$ 估算等效公差带宽。',
    tags: ['转换', '公差'],
    category: '统计',
  },
  {
    id: 'nominal-chain',
    name: '封闭环名义值',
    formula: 'L₀ = ΣL增 − ΣL减',
    latex: 'L_0 = \\sum L_{\\text{增}} - \\sum L_{\\text{减}}',
    desc: '增环与封闭环同向，减环反向，按传递系数加权。',
    tags: ['名义值', '增环', '减环'],
    category: '尺寸链',
  },
  {
    id: 'sigma-level',
    name: '西格玛水平',
    formula: 'σ水平 ≈ 3 × Cpk',
    latex: '\\sigma_{\\text{水平}} \\approx 3 \\cdot C_{pk}',
    desc: '由 $C_{pk}$ 换算的有效西格玛水平；$C_{pk}\\geq 1.33$ 时约对应 4σ 能力。',
    tags: ['西格玛', '质量'],
    category: '统计',
  },
  {
    id: 'cpk',
    name: '过程能力 Cpk',
    formula: 'Cpk = min[(USL−μ)/3σ, (μ−LSL)/3σ]',
    latex: 'C_{pk} = \\min\\left(\\frac{USL - \\mu}{3\\sigma}, \\frac{\\mu - LSL}{3\\sigma}\\right)',
    desc: '$C_{pk}$ 同时考虑规格上下限与过程中心是否偏移：取距 USL 和 LSL 较小侧除以 $3\\sigma$；$\\geq 1.33$ 通常视为过程能力良好。',
    tags: ['Cpk', 'SPC'],
    category: '统计',
  },
  {
    id: 'pass-rate',
    name: '合格率（正态近似）',
    formula: 'P = Φ(USL) − Φ(LSL)',
    latex: 'P = \\Phi(USL) - \\Phi(LSL)',
    desc: '在已知过程均值 $\\mu$ 与标准差 $\\sigma$ 时，对规格上下限 LSL/USL 积分正态分布得到规格内比例；过程中心偏移会显著降低合格率。',
    tags: ['合格率', '正态'],
    category: '统计',
  },
  {
    id: 'dppm',
    name: 'DPPM',
    formula: 'DPPM = (1 − P) × 10⁶',
    latex: 'DPPM = (1 - P) \\times 10^{6}',
    desc: '每百万件缺陷数，$P$ 为合格率。',
    tags: ['DPPM', '质量'],
    category: '统计',
  },
  {
    id: 'mean',
    name: '样本均值',
    formula: 'μ = Σx / n',
    latex: '\\mu = \\frac{\\sum x}{n}',
    desc: '测量数据的算术平均值。',
    tags: ['统计', '均值'],
    category: '统计',
  },
  {
    id: 'std',
    name: '样本标准差',
    formula: 'σ = √[Σ(x−μ)² / n]',
    latex: '\\sigma = \\sqrt{\\frac{\\sum (x - \\mu)^2}{n}}',
    desc: '总体标准差估计（与需求书一致）。',
    tags: ['统计', '标准差'],
    category: '统计',
  },
  {
    id: 'range',
    name: '极差',
    formula: 'R = x_max − x_min',
    latex: 'R = x_{\max} - x_{\min}',
    desc: '样本最大值与最小值之差。',
    tags: ['统计', '极差'],
    category: '统计',
  },
  {
    id: 'gear-pitch-diameter',
    name: '齿轮分度圆直径',
    formula: 'd = m × z',
    latex: 'd = m \\cdot z',
    desc: '直齿轮分度圆直径，$m$ 为模数 (mm)，$z$ 为齿数。',
    tags: ['齿轮', '几何'],
    category: '齿轮',
  },
  {
    id: 'gear-tangential-force',
    name: '齿轮圆周力',
    formula: 'Ft = 2000T / d',
    latex: 'F_t = \\frac{2000\\,T}{d}',
    desc: '由扭矩 $T$ (N·m) 与分度圆直径 $d$ (mm) 求圆周力 $F_t$ (N)。',
    tags: ['齿轮', '力学'],
    category: '齿轮',
  },
  {
    id: 'gear-bending-stress',
    name: '齿轮弯曲应力（Lewis）',
    formula: 'σF = Ft / (b·m·Y)',
    latex: '\\sigma_F = \\frac{F_t}{b \\cdot m \\cdot Y}',
    desc: 'Lewis 公式近似齿根弯曲应力 $\\sigma_F$ (MPa)。$b$ 为齿宽，$Y$ 为齿形系数（常用 2.5~2.8）。',
    tags: ['齿轮', '强度'],
    category: '齿轮',
  },
  {
    id: 'gear-contact-stress',
    name: '齿轮接触应力（简化）',
    formula: 'σH ≈ 118√[Ft(u+1)/(b·d·u)]',
    latex: '\\sigma_H \\approx 118\\sqrt{\\frac{F_t(u+1)}{b \\cdot d \\cdot u}}',
    desc: '钢制直齿轮赫兹接触应力简化估算 (MPa)，$\\sigma_H$ 为接触应力，$u$ 为齿数比（$\\geq 1$）。',
    tags: ['齿轮', '强度', '接触'],
    category: '齿轮',
  },
  {
    id: 'gear-pitch-velocity',
    name: '齿轮线速度',
    formula: 'v = πdn / 60000',
    latex: 'v = \\frac{\\pi d n}{60000}',
    desc: '分度圆线速度 $v$ (m/s)，$d$ 为分度圆直径 (mm)，$n$ 为转速 (rpm)。',
    tags: ['齿轮', '运动学'],
    category: '齿轮',
  },
  {
    id: 'bearing-equivalent-load',
    name: '轴承当量动载荷',
    formula: 'P = X·Fr + Y·Fa',
    latex: 'P = X \\cdot F_r + Y \\cdot F_a',
    desc: '滚动轴承径向/轴向合成当量动载荷 $P$ (N)，$X$/$Y$ 取自轴承手册或工况系数。',
    tags: ['轴承', '载荷'],
    category: '轴承',
  },
  {
    id: 'bearing-l10',
    name: '轴承额定寿命 L10',
    formula: 'L10 = (C/P)^ε（百万转）',
    latex: 'L_{10} = \\left(\\frac{C}{P}\\right)^{\\varepsilon}',
    desc: 'ISO 281 基本额定寿命，$C$ 为额定动载荷 (N)。球轴承 $\\varepsilon=3$，滚子轴承 $\\varepsilon=10/3$。',
    tags: ['轴承', '寿命'],
    category: '轴承',
  },
  {
    id: 'bearing-life-hours',
    name: '轴承寿命（小时）',
    formula: 'Lh = L10×10⁶ / (60n)',
    latex: 'L_h = \\frac{L_{10} \\times 10^{6}}{60 \\cdot n}',
    desc: '由 $L_{10}$（百万转）与转速 $n$ (rpm) 换算为小时寿命 $L_h$。',
    tags: ['轴承', '寿命'],
    category: '轴承',
  },
  {
    id: 'iso6336-contact',
    name: 'ISO 6336 接触应力',
    formula: 'σH = ZB·ZH·ZE·Zε·√(Ft/bd1·(u+1)/u·KA·KV·KHβ·KHα)',
    latex: '\\sigma_H = Z_B Z_H Z_E Z_\\varepsilon \\sqrt{\\frac{F_t}{b d_1}\\frac{u+1}{u} K_A K_V K_{H\\beta} K_{H\\alpha}}',
    desc: 'ISO 6336-2 齿面接触应力，$S_H = \\sigma_{H\\lim}/\\sigma_H$。',
    tags: ['ISO 6336', '齿轮', '接触'],
    category: '齿轮',
  },
  {
    id: 'iso6336-bending',
    name: 'ISO 6336 弯曲应力',
    formula: 'σF = Ft/(b·mn)·YF·YS·Yβ·KA·KV·KFβ·KFα',
    latex: '\\sigma_F = \\frac{F_t}{b m_n} Y_F Y_S Y_\\beta K_A K_V K_{F\\beta} K_{F\\alpha}',
    desc: 'ISO 6336-3 齿根弯曲应力，$S_F = \\sigma_{F\\lim}/\\sigma_F$。',
    tags: ['ISO 6336', '齿轮', '弯曲'],
    category: '齿轮',
  },
  {
    id: 'shaft-torsion',
    name: '轴扭转切应力',
    formula: 'τ = 16T / (πd³)',
    latex: '\\tau = \\frac{16 T}{\\pi d^3}',
    desc: '实心圆轴扭转最大切应力 $\\tau$ (MPa)，$T$ 单位 N·m，$d$ 单位 mm。',
    tags: ['轴', '扭转'],
    category: '结构',
  },
  {
    id: 'spring-rate',
    name: '弹簧刚度',
    formula: 'k = Gd⁴ / (8D³n)',
    latex: 'k = \\frac{G d^4}{8 D^3 n}',
    desc: '圆柱螺旋压缩弹簧刚度 $k$ (N/mm)。',
    tags: ['弹簧'],
    category: '结构',
  },
  {
    id: 'belt-length',
    name: '开口皮带长度',
    formula: 'L = 2C + π(D1+D2)/2 + (D2-D1)²/(4C)',
    latex: 'L = 2C + \\frac{\\pi(D_1+D_2)}{2} + \\frac{(D_2-D_1)^2}{4C}',
    desc: '开口皮带传动几何长度估算。',
    tags: ['皮带'],
    category: '传动',
  },
  {
    id: 'cylinder-force',
    name: '液压缸推力',
    formula: 'F = p·A / 1000',
    latex: 'F = \\frac{p \\cdot A}{1000}',
    desc: '$p$ 为压力 (MPa)，$A$ 为活塞面积 (mm²)，$F$ 为力 (N)。',
    tags: ['液压', '气缸'],
    category: '流体',
  },
  {
    id: 'thread-stress-area',
    name: '螺纹有效截面积',
    formula: 'As = π/4 × (d − 0.9382P)²',
    latex: 'A_s = \\frac{\\pi}{4}(d - 0.9382P)^2',
    desc: '公制螺纹有效截面积 (mm²)，用于拉应力计算。',
    tags: ['螺纹', '强度'],
    category: '螺纹',
  },
  {
    id: 'thread-tensile',
    name: '螺纹拉应力',
    formula: 'σ = F / As',
    latex: '\\sigma = \\frac{F}{A_s}',
    desc: '轴向载荷 $F$ (N) 与有效面积 $A_s$ 求拉应力 $\\sigma$ (MPa)。',
    tags: ['螺纹', '强度'],
    category: '螺纹',
  },
  {
    id: 'thread-torque',
    name: '螺纹拧紧扭矩',
    formula: 'T = μdF / 1000',
    latex: 'T = \\frac{\\mu d F}{1000}',
    desc: '摩擦系数 $\\mu$，公称直径 $d$ (mm)，预紧力 $F$ (N)，扭矩 $T$ (N·m)。',
    tags: ['螺纹', '扭矩'],
    category: '螺纹',
  },
  {
    id: 'shaft-combined',
    name: '弯扭合成应力',
    formula: 'σeq = √(σ² + 3τ²)',
    latex: '\\sigma_{eq} = \\sqrt{\\sigma^2 + 3\\tau^2}',
    desc: '第四强度理论，由弯曲正应力 $\\sigma$ 与扭转切应力 $\\tau$ 求当量应力 $\\sigma_{eq}$ (MPa)。',
    tags: ['轴', '弯扭'],
    category: '结构',
  },
  {
    id: 'key-crushing',
    name: '平键挤压应力',
    formula: 'σp = 2T / (d·k·l·h)',
    latex: '\\sigma_p = \\frac{2T}{d \\cdot k \\cdot l \\cdot h}',
    desc: '$T$ 为扭矩 (N·m)，$d$ 为轴径，$k$ 为工作长度系数，$l$/$h$ 为键工作尺寸 (mm)。',
    tags: ['平键', '挤压'],
    category: '结构',
  },
  {
    id: 'weld-throat',
    name: '角焊缝有效厚度',
    formula: 'a = 0.7·s',
    latex: 'a = 0.7 \\cdot s',
    desc: '$s$ 为焊脚尺寸 (mm)，$a$ 为有效喉厚，用于剪切/正应力校核。',
    tags: ['焊缝', '角焊'],
    category: '结构',
  },
  {
    id: 'bolt-group-eccentric',
    name: '螺栓组偏心载荷',
    formula: 'Fi = P/n + M·ri / Σri²',
    latex: 'F_i = \\frac{P}{n} + \\frac{M \\cdot r_i}{\\sum r_i^2}',
    desc: '偏心弯矩 $M$ 引起附加拉力，与轴向载荷 $P$ 均分到各螺栓 $F_i$。',
    tags: ['螺栓组', '偏心'],
    category: '结构',
  },
  {
    id: 'alloc-sensitivity',
    name: '灵敏度 RSS 分配',
    formula: 'Tᵢ ∝ sᵢ·fᵢ',
    latex: 'T_i \\propto s_i \\cdot f_i',
    desc: '按灵敏度系数 $s$ 与传递系数 $f$ 加权分配 RSS 公差预算。',
    tags: ['分配', '灵敏度', 'RSS'],
    category: '尺寸链',
  },
  {
    id: 'gdt-mmc-bonus',
    name: 'GD&T MMC 奖励公差',
    formula: 'T_eff = T + Δ_bonus (MMC)',
    latex: 'T_{eff} = T + \\Delta_{bonus}\\ (\\text{MMC})',
    desc: '最大实体条件下，位置/形状公差带可随尺寸偏离 MMC 而扩大，$T_{\\mathrm{eff}} = T + \\Delta_{\\mathrm{bonus}}$。',
    tags: ['GD&T', 'MMC', '奖励'],
    category: '尺寸链',
  },
  {
    id: 'agma-contact',
    name: 'AGMA 接触应力',
    formula: 'σc = Cp √[Wt·Ko·Kv·Km/(b·d·I) · (u+1)/u]',
    latex: '\\sigma_c = C_p \\sqrt{\\frac{W_t K_o K_v K_m}{b d I} \\cdot \\frac{u+1}{u}}',
    desc: 'AGMA 2101 简化接触应力 $\\sigma_c$，$C_p \\approx 190\\,(\\mathrm{N/mm^2})^{0.5}$，$I$ 为几何系数。',
    tags: ['AGMA', '齿轮', '接触'],
    category: '齿轮',
  },
  {
    id: 'agma-bending',
    name: 'AGMA 弯曲应力',
    formula: 'σt = Wt·Ko·Kv·Km·Ks / (b·m·J)',
    latex: '\\sigma_t = \\frac{W_t K_o K_v K_m K_s}{b m J}',
    desc: 'AGMA 2101 简化齿根弯曲应力 $\\sigma_t$，$J$ 为几何系数。',
    tags: ['AGMA', '齿轮', '弯曲'],
    category: '齿轮',
  },
  {
    id: 'iso1328-fpt',
    name: 'ISO 1328 单齿距偏差',
    formula: 'f_pt ≈ k(grade) · (0.42√m + 0.12√d)',
    latex: 'f_{pt} \\approx k(\\text{grade}) \\cdot (0.42\\sqrt{m} + 0.12\\sqrt{d})',
    desc: '齿轮精度等级对应的单齿距偏差 $f_{pt}$ 估算 ($\\mu$m)，与 ISO 6336 $K_V$ 联动。',
    tags: ['ISO 1328', '齿轮', '精度'],
    category: '齿轮',
  },
  {
    id: 'darcy-weisbach',
    name: 'Darcy-Weisbach 压降',
    formula: 'ΔP = f · (L/D) · (ρv²/2)',
    latex: '\\Delta P = f \\cdot \\frac{L}{D} \\cdot \\frac{\\rho v^2}{2}',
    desc: '沿程摩擦压降 $\\Delta P$，$f$ 为摩擦系数，$L/D$ 为长径比。',
    tags: ['流体', '管路', '压降'],
    category: '流体',
  },
  {
    id: 'plate-buckling',
    name: '薄板屈曲临界应力',
    formula: 'σcr = k · π² · E / (12(1-ν²)) · (t/b)²',
    latex: '\\sigma_{cr} = k \\cdot \\frac{\\pi^2 E}{12(1-\\nu^2)} \\cdot \\left(\\frac{t}{b}\\right)^2',
    desc: '矩形板单轴压缩弹性屈曲，$\\sigma_{cr}$ 为临界应力，$k$ 取决于边界条件。',
    tags: ['屈曲', '薄板', '结构'],
    category: '结构',
  },
  {
    id: 'miner-damage',
    name: 'Miner 累积损伤',
    formula: 'D = Σ (ni / Ni)',
    latex: 'D = \\sum \\frac{n_i}{N_i}',
    desc: '疲劳载荷谱线性累积，$D \\geq 1$ 时认为疲劳失效。',
    tags: ['疲劳', 'Miner', 'S-N'],
    category: '疲劳',
  },
  {
    id: 'sheet-metal-ba',
    name: '钣金折弯补偿',
    formula: 'BA = (π/180) · θ · (R + K·T)',
    latex: 'BA = \\frac{\\pi}{180} \\cdot \\theta \\cdot (R + K \\cdot T)',
    desc: '$K$ 因子法折弯补偿量，$\\theta$ 为折弯角，$R$ 为内半径，$T$ 为板厚。',
    tags: ['钣金', 'K因子', '展开'],
    category: '制造',
  },
  {
    id: 'machining-allowance',
    name: '机加工余量',
    formula: 'D_stock = D_part + 2Σa_i',
    latex: 'D_{stock} = D_{part} + 2\\sum a_i',
    desc: '各工序单面余量 $a_i$ 叠加得到推荐毛坯直径 $D_{\\mathrm{stock}}$。',
    tags: ['机加工', '余量', '毛坯'],
    category: '制造',
  },
  {
    id: 'casting-draft',
    name: '铸造拔模斜度',
    formula: 'α ≥ α_base + k·√h',
    latex: '\\alpha \\geq \\alpha_{base} + k\\sqrt{h}',
    desc: '拔模高度 $h$ 越大，所需拔模角 $\\alpha$ 越大，内腔取更大系数。',
    tags: ['铸造', '拔模', '工艺'],
    category: '制造',
  },
  {
    id: 'fmea-rpn',
    name: 'FMEA 风险优先数',
    formula: 'RPN = S × O × D',
    latex: 'RPN = S \\times O \\times D',
    desc: '严重度 $S$、发生度 $O$、探测度 $D$ 的乘积，用于排序改进优先级。',
    tags: ['FMEA', '质量', 'RPN'],
    category: '质量',
  },
  {
    id: 'carbon-equivalent',
    name: '碳当量 CE',
    formula: 'CE = C + Mn/6 + (Cr+Mo+V)/5 + (Ni+Cu)/15',
    latex: 'CE = C + \\frac{Mn}{6} + \\frac{Cr+Mo+V}{5} + \\frac{Ni+Cu}{15}',
    desc: 'IIW 碳当量，用于评估淬硬性与焊接裂纹敏感性。',
    tags: ['热处理', '碳当量', '焊接'],
    category: '材料',
  },
  {
    id: 'hollomon-jaffe',
    name: 'Hollomon-Jaffe 参数',
    formula: 'PJ = T(20 + log t)',
    latex: 'PJ = T(20 + \\log t)',
    desc: '回火温度 $T$ (K) 与保温时间 $t$ (s) 的综合参数，等 $P_J$ 对应相近硬度。',
    tags: ['热处理', '回火', '硬度'],
    category: '材料',
  },
  {
    id: 'rsm-quadratic',
    name: '响应面二次模型',
    formula: 'y = β₀ + β₁x₁ + β₂x₂ + β₁₂x₁x₂ + β₁₁x₁² + β₂₂x₂²',
    latex: 'y = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\beta_{12} x_1 x_2 + \\beta_{11} x_1^2 + \\beta_{22} x_2^2',
    desc: '二因子中心复合设计 (CCD) 常用二次响应面模型。',
    tags: ['DOE', 'RSM', '响应面'],
    category: '统计',
  },
  {
    id: 'iso286-fit',
    name: 'ISO 286 配合间隙',
    formula: 'C_max = D_max − d_min',
    latex: 'C_{max} = D_{max} - d_{min}',
    desc: '孔最大尺寸减轴最小尺寸得最大间隙 $C_{\\max}$；过盈配合时为负值。',
    tags: ['ISO286', '公差', '配合'],
    category: '公差',
  },
  {
    id: 'it-tolerance',
    name: '标准公差 IT',
    formula: 'IT = i × 等级系数',
    latex: 'IT = i \\times \\text{grade factor}',
    desc: '$i = 0.45\\sqrt[3]{D} + 0.001D$ ($\\mu$m)，$D$ 为公称尺寸 (mm)。',
    tags: ['ISO286', 'IT', '公差'],
    category: '公差',
  },
  {
    id: 'weld-ec3',
    name: 'Eurocode 角焊缝许用剪应力',
    formula: 'τ_Rd = fu / (√3 · βw · γM2)',
    latex: '\\tau_{Rd} = \\frac{f_u}{\\sqrt{3}\\,\\beta_w\\,\\gamma_{M2}}',
    desc: 'EN 1993-1-8 角焊缝抗剪强度简化公式。',
    tags: ['焊缝', 'Eurocode', 'EC3'],
    category: '强度',
  },
  {
    id: 'gdt-datum-stack',
    name: 'GD&T 基准累积',
    formula: 'T_datum = √(Σ(wi·Ti)²)',
    latex: 'T_{datum} = \\sqrt{\\sum (w_i T_i)^2}',
    desc: '多基准面 flatness/perpendicularity 加权 RSS 叠加得 $T_{\\mathrm{datum}}$。',
    tags: ['GD&T', '基准', '栈'],
    category: '公差',
  },
]
