export const FORMULAS = [
  {
    id: 'worst-case',
    name: '极值法（最坏情况）',
    formula: 'T = T₁ + T₂ + T₃ + …',
    latex: 'T = T_1 + T_2 + T_3 + \cdots',
    desc: '各组成环公差代数相加，结果最保守，适用于 100% 安全要求。',
    tags: ['极值', '公差', '尺寸链'],
  },
  {
    id: 'rss',
    name: 'RSS 法（概率法）',
    formula: 'T = √(T₁² + T₂² + T₃² + …)',
    latex: 'T = \sqrt{T_1^2 + T_2^2 + T_3^2 + \cdots}',
    desc: '独立变量假设下的统计叠加，一般对应约 95% 合格率。',
    tags: ['RSS', '概率', '公差'],
  },
  {
    id: 'modified-rss',
    name: '修正 RSS 法',
    formula: 'T_mod = k × √(T₁² + T₂² + …)',
    latex: 'T_{mod} = k \\cdot \\sqrt{T_1^2 + T_2^2 + \\cdots}',
    desc: '在 RSS 基础上乘以分布修正系数 k，适用于均匀/偏态等非正态场景。',
    tags: ['RSS', '修正', '偏态'],
  },
  {
    id: 'weighted-rss',
    name: '加权 RSS',
    formula: 'T = √(Σ(T×f)²)',
    latex: 'T = \\sqrt{\\sum (T_i \\cdot f_i)^2}',
    desc: '传递系数加权的 RSS 叠加。',
    tags: ['RSS', '加权'],
  },
  {
    id: 't-to-sigma',
    name: '公差 → 标准差',
    formula: 'σ = T / K',
    latex: '\\sigma = \\frac{T}{K}',
    desc: 'K 为分布系数：正态 6.0，均匀 3.46，三角 4.24，偏态 5.0。',
    tags: ['转换', '正态', '标准差'],
  },
  {
    id: 'sigma-to-t',
    name: '标准差 → 公差',
    formula: 'T = σ × K',
    latex: 'T = \\sigma \cdot K',
    desc: '由过程标准差估算等效公差带宽。',
    tags: ['转换', '公差'],
  },
  {
    id: 'nominal-chain',
    name: '封闭环名义值',
    formula: 'L₀ = ΣL增 − ΣL减',
    latex: 'L_0 = \sum L_{\text{增}} - \sum L_{\text{减}}',
    desc: '增环与封闭环同向，减环反向，按传递系数加权。',
    tags: ['名义值', '增环', '减环'],
  },
  {
    id: 'sigma-level',
    name: '西格玛水平',
    formula: 'σ水平 = T目标 / (6σ)',
    latex: '\\sigma_{\text{水平}} = \\frac{T_{\text{目标}}}{6\\sigma}',
    desc: '衡量过程满足目标公差的能力，越大越好。',
    tags: ['西格玛', '质量'],
  },
  {
    id: 'cpk',
    name: '过程能力 Cpk',
    formula: 'Cpk = min[(USL−μ)/3σ, (μ−LSL)/3σ]',
    latex: 'C_{pk} = \min\\left(\frac{USL - \mu}{3\\sigma}, \frac{\mu - LSL}{3\\sigma}\right)',
    desc: '同时考虑上下规格限与过程中心偏移。',
    tags: ['Cpk', 'SPC'],
  },
  {
    id: 'pass-rate',
    name: '合格率（正态近似）',
    formula: 'P = 2Φ(σ水平) − 1',
    latex: 'P = 2\Phi(\\sigma_{\text{水平}}) - 1',
    desc: '基于正态分布 CDF 估算规格内比例。',
    tags: ['合格率', '正态'],
  },
  {
    id: 'dppm',
    name: 'DPPM',
    formula: 'DPPM = (1 − P) × 10⁶',
    latex: 'DPPM = (1 - P) \times 10^{6}',
    desc: '每百万件缺陷数，P 为合格率。',
    tags: ['DPPM', '质量'],
  },
  {
    id: 'mean',
    name: '样本均值',
    formula: 'μ = Σx / n',
    latex: '\\mu = \\frac{\sum x}{n}',
    desc: '测量数据的算术平均值。',
    tags: ['统计', '均值'],
  },
  {
    id: 'std',
    name: '样本标准差',
    formula: 'σ = √[Σ(x−μ)² / n]',
    latex: '\\sigma = \sqrt{\\frac{\sum (x - \\mu)^2}{n}}',
    desc: '总体标准差估计（与需求书一致）。',
    tags: ['统计', '标准差'],
  },
  {
    id: 'range',
    name: '极差',
    formula: 'R = x_max − x_min',
    latex: 'R = x_{\max} - x_{\min}',
    desc: '样本最大值与最小值之差。',
    tags: ['统计', '极差'],
  },
]
