export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: '什么是封闭环？',
    options: [
      { value: 'a', label: '装配最终形成的尺寸' },
      { value: 'b', label: '任意一个零件尺寸' },
      { value: 'c', label: '公差最大的组成环' },
      { value: 'd', label: '第一个输入的尺寸' },
    ],
    answer: 'a',
    answerLabel: '装配最终形成的尺寸',
    explain: '封闭环是在装配完成后间接得到的尺寸，如间隙或过盈量。',
  },
  {
    id: 2,
    question: 'RSS 法的总公差公式是？',
    options: [
      { value: 'a', label: '$T = \\sum T_i$' },
      { value: 'b', label: '$T = \\sqrt{\\sum T_i^2}$' },
      { value: 'c', label: '$T = T_1 \\times T_2$' },
      { value: 'd', label: '$T = \\max(T_i)$' },
    ],
    answer: 'b',
    answerLabel: '$T = \\sqrt{\\sum T_i^2}$',
    explain: 'RSS（Root Sum Square）法假设各环独立，按平方和开方叠加公差。',
  },
  {
    id: 3,
    question: '增环是指？',
    options: [
      { value: 'a', label: '与封闭环同向的组成环' },
      { value: 'b', label: '与封闭环反向的组成环' },
      { value: 'c', label: '公差最大的环' },
      { value: 'd', label: '第一个添加的环' },
    ],
    answer: 'a',
    answerLabel: '与封闭环同向的组成环',
    explain: '1D 尺寸链中，方向与封闭环相同的组成环为增环，反之为减环。',
  },
  {
    id: 4,
    question: '极值法适用于什么情况？',
    options: [
      { value: 'a', label: '要求 100% 安全裕度的最坏情况' },
      { value: 'b', label: '一般批量生产的概率分析' },
      { value: 'c', label: '仅适用于 2D 分析' },
      { value: 'd', label: '仅适用于 GD&T' },
    ],
    answer: 'a',
    answerLabel: '要求 100% 安全裕度的最坏情况',
    explain: '极值法将所有环公差代数相加，结果最保守，适合高安全要求场景。',
  },
  {
    id: 5,
    question: '正态分布下，公差 $T$ 与标准差 $\\sigma$ 的关系（6σ）是？',
    options: [
      { value: 'a', label: '$T = 3\\sigma$' },
      { value: 'b', label: '$T = 6\\sigma$' },
      { value: 'c', label: '$T = \\sigma^2$' },
      { value: 'd', label: '$T = 2\\sigma$' },
    ],
    answer: 'b',
    answerLabel: '$T = 6\\sigma$',
    explain: '正态分布 $K=6$，即公差带宽约等于 $\\pm 3\\sigma$，总带宽 $T \\approx 6\\sigma$。',
  },
  {
    id: 6,
    question: '减环对封闭环尺寸的影响是？',
    options: [
      { value: 'a', label: '使封闭环增大' },
      { value: 'b', label: '使封闭环减小' },
      { value: 'c', label: '无影响' },
      { value: 'd', label: '仅影响公差' },
    ],
    answer: 'b',
    answerLabel: '使封闭环减小',
    explain: '减环在尺寸链公式中取负号，尺寸增大则封闭环减小。',
  },
  {
    id: 7,
    question: '$C_{pk} > 1.33$ 通常表示？',
    options: [
      { value: 'a', label: '过程能力优秀' },
      { value: 'b', label: '一定不合格' },
      { value: 'c', label: '仅适用于 RSS' },
      { value: 'd', label: '与公差无关' },
    ],
    answer: 'a',
    answerLabel: '过程能力优秀',
    explain: 'Cpk 反映过程满足规格的能力，>1.33 是常用的优秀水平参考。',
  },
  {
    id: 8,
    question: '传递系数的作用是？',
    options: [
      { value: 'a', label: '加权放大或缩小该环对封闭环的影响' },
      { value: 'b', label: '改变增/减环类型' },
      { value: 'c', label: '切换 mm/inch' },
      { value: 'd', label: '选择计算方法' },
    ],
    answer: 'a',
    answerLabel: '加权放大或缩小该环对封闭环的影响',
    explain: '传递系数用于非 1:1 关系，如角度误差、杠杆比等场景。',
  },
  {
    id: 9,
    question: '尺寸链合格判定（目标范围 $[min,max]$）的正确条件是？',
    options: [
      { value: 'a', label: '计算下限 $\\ge min$ 且 计算上限 $\\le max$' },
      { value: 'b', label: '名义值等于 $(min+max)/2$' },
      { value: 'c', label: 'RSS 总公差 $< max$' },
      { value: 'd', label: '极值法总公差 $=$ RSS 总公差' },
    ],
    answer: 'a',
    answerLabel: '计算下限 $\\ge min$ 且 计算上限 $\\le max$',
    explain: '封闭环的计算区间必须完全落在目标规格范围内才算合格。',
  },
  {
    id: 10,
    question: '均匀分布的 $K$ 值（标准差系数）约为？',
    options: [
      { value: 'a', label: '$6.0$' },
      { value: 'b', label: '$3.46$' },
      { value: 'c', label: '$4.24$' },
      { value: 'd', label: '$5.0$' },
    ],
    answer: 'b',
    answerLabel: '$3.46$',
    explain: '均匀分布 $K \\approx 3.46$，正态 $6.0$，三角 $4.24$，偏态 $5.0$。',
  },
]
