/**
 * 螺纹总分类注册表 — 按一级用途 / 二级族系 / 标准体系统一描述
 * 已实现规格表者 catalog 指向 THREAD_SYSTEMS；其余为参考元数据（implemented: false）
 */

/** @typedef {'fastener'|'pipe'|'power'|'special'|'oil'|'aerospace'|'industry'} ThreadPurposeId */
/** @typedef {'triangular'|'trapezoidal'|'square'|'buttress'|'round'|'ball_screw'} ThreadProfileId */
/** @typedef {'cylindrical'|'conical'} ParentShapeId */
/** @typedef {'parallel'|'taper'} TaperKindId */
/** @typedef {'none'|'taper_metal'|'gasket'|'dry_seal'} SealingKindId */
/** @typedef {'P_mm'|'TPI'|'lead_mm'|null} ThreadPitchNotationId */
/** @typedef {'mm'|'in'|'mm_in'|null} ThreadUnitId */

/**
 * @typedef {object} ThreadSystemDef
 * @property {string} id
 * @property {ThreadPurposeId} purpose
 * @property {string} family 二级分类 id
 * @property {boolean} implemented
 * @property {{ system: string, subTab: string }|null} catalog
 * @property {ThreadProfileId} profile
 * @property {number|null} angle
 * @property {string|null} angleLabel
 * @property {ParentShapeId} parentShape
 * @property {TaperKindId} taper
 * @property {string|null} taperRatio
 * @property {SealingKindId} sealing
 * @property {('RH'|'LH')[]} hand
 * @property {('single'|'multi')[]} starts
 * @property {ThreadUnitId} unit
 * @property {ThreadPitchNotationId} pitchNotation
 * @property {string|null} gbStandard
 * @property {string|null} markingExample
 * @property {string[]} standards
 * @property {number} [diagramAngle]
 */

export const THREAD_PURPOSE_ORDER = /** @type {ThreadPurposeId[]} */ ([
  'fastener',
  'pipe',
  'power',
  'special',
  'oil',
  'aerospace',
  'industry',
])

/** 二级分类展示顺序（按一级分组） */
export const THREAD_FAMILY_ORDER = [
  'metric_fastener',
  'unified_fastener',
  'whitworth_fastener',
  'obsolete_fastener',
  'npt_pipe',
  'bsp_pipe',
  'jis_pipe',
  'trap_power',
  'other_power',
  'round_special',
  'instrument_special',
  'self_tap_special',
  'gas_cylinder_special',
  'api_round',
  'api_trap',
  'api_special',
  'aero_strength',
  'aero_pipe',
  'aero_std',
  'building_industry',
  'mining_industry',
  'consumer_industry',
]

/**
 * @param {Partial<ThreadSystemDef> & Pick<ThreadSystemDef, 'id'|'purpose'|'family'>} partial
 * @returns {ThreadSystemDef}
 */
function sys(partial) {
  return {
    implemented: false,
    catalog: null,
    profile: 'triangular',
    angle: 60,
    angleLabel: '60°',
    parentShape: 'cylindrical',
    taper: 'parallel',
    taperRatio: null,
    sealing: 'none',
    hand: ['RH', 'LH'],
    starts: ['single'],
    unit: 'mm',
    pitchNotation: 'P_mm',
    gbStandard: null,
    markingExample: null,
    standards: [],
    diagramAngle: 60,
    ...partial,
  }
}

/** @type {Record<ThreadPurposeId, string[]>} */
export const PURPOSE_SYSTEM_IDS = {
  fastener: [
    'metric_coarse',
    'mj',
    'unc',
    'unf',
    'unef',
    'uns',
    'un',
    'unj',
    'unjc',
    'unjf',
    'whitworth',
    'bsw',
    'bsf',
    'ba',
    'v_sharp',
  ],
  pipe: [
    'npt',
    'nptf',
    'nps',
    'npsm',
    'npsl',
    'npsh',
    'npsc',
    'nptr',
    'nh',
    'npsf',
    'npsi',
    'anpt',
    'bspp_g',
    'bspt_r',
    'bspt_rc',
    'bspt_rp',
    'bspt_r12',
    'pt_jis',
    'pf_jis',
  ],
  power: [
    'tr',
    'acme',
    'stub_acme',
    'tr_multi',
    'square',
    'buttress',
    'buttress_din513',
    'module_din5480',
    'ball_screw',
  ],
  special: [
    'rd',
    'knuckle',
    'arc_round',
    'edison',
    'bottle',
    'microscope',
    'optical',
    'rms_objective',
    'self_tap_st',
    'self_tap_lock',
    'heli_coil',
    'gas_cylinder',
    'gas_cylinder_taper',
  ],
  oil: [
    'api_stc',
    'api_ltc',
    'api_nue',
    'api_eue',
    'api_btc',
    'api_xc',
    'api_premium',
  ],
  aerospace: [
    'aero_unj',
    'aero_mj',
    'aero_unjf',
    'aero_unjc',
    'aero_anpt',
    'nas',
  ],
  industry: [
    'rebar_straight',
    'rebar_taper',
    'rebar_swage',
    'drill_rod_r',
    'drill_rod_t',
    'bicycle',
    'watch',
  ],
}

/** @type {Record<string, ThreadSystemDef>} */
export const THREAD_SYSTEM_REGISTRY = {
  // —— 紧固 / 公制 ——
  metric_coarse: sys({
    id: 'metric_coarse',
    purpose: 'fastener',
    family: 'metric_fastener',
    implemented: true,
    catalog: { system: 'metric', subTab: 'all' },
    gbStandard: 'GB/T 196-2003',
    markingExample: 'M16',
    standards: ['ISO 68-1', 'ISO 724', 'ISO 965'],
  }),
  /** @deprecated 已并入 metric_coarse 统一表；保留定义供旧路由/对照，不出现在左侧导航 */
  metric_fine: sys({
    id: 'metric_fine',
    purpose: 'fastener',
    family: 'metric_fastener',
    implemented: true,
    catalog: { system: 'metric', subTab: 'all' },
    gbStandard: 'GB/T 197-2003',
    markingExample: 'M16×1.5',
    standards: ['ISO 68-1', 'ISO 724', 'ISO 965'],
  }),
  /** @deprecated 无独立主表；不出现在左侧导航 */
  metric_extra_fine: sys({
    id: 'metric_extra_fine',
    purpose: 'fastener',
    family: 'metric_fastener',
    gbStandard: 'GB/T 15054-1994',
    markingExample: 'M8×0.75',
    standards: ['ISO 1502'],
  }),
  /** @deprecated 无独立主表；不出现在左侧导航 */
  metric_small_s: sys({
    id: 'metric_small_s',
    purpose: 'fastener',
    family: 'metric_fastener',
    gbStandard: 'GB/T 15054-1994',
    markingExample: 'S0.8×0.2',
    standards: ['ISO 1501'],
  }),
  mj: sys({
    id: 'mj',
    purpose: 'fastener',
    family: 'metric_fastener',
    angleLabel: '60°圆弧牙底',
    gbStandard: 'GJB 3.1-1982',
    markingExample: 'MJ6×1',
    standards: ['ISO 5855'],
  }),

  // —— 紧固 / 统一 ——
  unc: sys({
    id: 'unc',
    purpose: 'fastener',
    family: 'unified_fastener',
    implemented: true,
    catalog: { system: 'unc', subTab: 'unc' },
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 20666-2006',
    markingExample: '3/8-16UNC',
    standards: ['ISO 68-2', 'ISO 263', 'ISO 5864'],
  }),
  unf: sys({
    id: 'unf',
    purpose: 'fastener',
    family: 'unified_fastener',
    implemented: true,
    catalog: { system: 'unf', subTab: 'unf' },
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 20666-2006',
    markingExample: '5/16-24UNF',
    standards: ['ISO 68-2', 'ISO 263', 'ISO 5864'],
  }),
  unef: sys({
    id: 'unef',
    purpose: 'fastener',
    family: 'unified_fastener',
    implemented: true,
    catalog: { system: 'unef', subTab: 'unef' },
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 20666-2006',
    markingExample: '1/4-32UNEF',
    standards: ['ISO 68-2', 'ISO 263', 'ISO 5864'],
  }),
  uns: sys({
    id: 'uns',
    purpose: 'fastener',
    family: 'unified_fastener',
    hand: ['RH', 'LH'],
    starts: ['single', 'multi'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 20666-2006',
    markingExample: '1/4-28UNS',
    standards: ['ISO 68-2', 'ISO 263', 'ISO 5864'],
  }),
  un: sys({
    id: 'un',
    purpose: 'fastener',
    family: 'unified_fastener',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 20666-2006',
    markingExample: '1/4-20UN',
    standards: ['ASME B1.1'],
  }),
  unj: sys({
    id: 'unj',
    purpose: 'fastener',
    family: 'unified_fastener',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.1-1982',
    markingExample: '1/4-28UNJF',
    standards: ['ASME B1.15'],
  }),
  unjc: sys({
    id: 'unjc',
    purpose: 'fastener',
    family: 'unified_fastener',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.3-1982',
    markingExample: '1/4-28UNJC',
    standards: ['ASME B1.15'],
  }),
  unjf: sys({
    id: 'unjf',
    purpose: 'fastener',
    family: 'unified_fastener',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.2-1982',
    markingExample: '1/4-28UNJF',
    standards: ['ASME B1.15'],
  }),

  // —— 紧固 / 惠氏 ——
  whitworth: sys({
    id: 'whitworth',
    purpose: 'fastener',
    family: 'whitworth_fastener',
    angle: 55,
    angleLabel: '55°',
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: 'W1/2-12',
    standards: ['BS 84-2007'],
    diagramAngle: 55,
  }),
  bsw: sys({
    id: 'bsw',
    purpose: 'fastener',
    family: 'whitworth_fastener',
    angle: 55,
    angleLabel: '55°',
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: '1/2-12BSW',
    standards: ['BS 84-2007'],
    diagramAngle: 55,
  }),
  bsf: sys({
    id: 'bsf',
    purpose: 'fastener',
    family: 'whitworth_fastener',
    angle: 55,
    angleLabel: '55°',
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: '1/2-16BSF',
    standards: ['BS 84-2007'],
    diagramAngle: 55,
  }),
  ba: sys({
    id: 'ba',
    purpose: 'fastener',
    family: 'whitworth_fastener',
    angle: 47.5,
    angleLabel: '47.5°',
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: 'BA6',
    standards: ['BS 93'],
    diagramAngle: 48,
  }),

  // —— 紧固 / 已淘汰 ——
  v_sharp: sys({
    id: 'v_sharp',
    purpose: 'fastener',
    family: 'obsolete_fastener',
    angleLabel: '60°尖牙',
    unit: null,
    pitchNotation: null,
    standards: [],
  }),

  // —— 管 / 美制 ——
  npt: sys({
    id: 'npt',
    purpose: 'pipe',
    family: 'npt_pipe',
    implemented: true,
    catalog: { system: 'npt', subTab: 'npt' },
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPT 3/4',
    standards: ['ASME B1.20.1'],
  }),
  nptf: sys({
    id: 'nptf',
    purpose: 'pipe',
    family: 'npt_pipe',
    implemented: true,
    catalog: { system: 'nptf', subTab: 'nptf' },
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'dry_seal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPTF 3/4',
    standards: ['ANSI B1.20.3'],
  }),
  nps: sys({
    id: 'nps',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPS 1/2',
    standards: ['ASME B1.20.1'],
  }),
  npsm: sys({
    id: 'npsm',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSM 1/2',
    standards: ['ASME B1.20.1'],
  }),
  npsl: sys({
    id: 'npsl',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSL 1/2',
    standards: ['ASME B1.20.1'],
  }),
  npsh: sys({
    id: 'npsh',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSH 3/4',
    standards: ['ASME B1.20.1'],
  }),
  npsc: sys({
    id: 'npsc',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSC 3/4',
    standards: ['ASME B1.20.1'],
  }),
  nptr: sys({
    id: 'nptr',
    purpose: 'pipe',
    family: 'npt_pipe',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPTR 3/4',
    standards: ['ASME B1.20.1'],
  }),
  nh: sys({
    id: 'nh',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NH 2.5-7.5',
    standards: ['NFPA 1963'],
  }),
  npsf: sys({
    id: 'npsf',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'dry_seal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSF 3/8',
    standards: ['ASME B1.20.3'],
  }),
  npsi: sys({
    id: 'npsi',
    purpose: 'pipe',
    family: 'npt_pipe',
    sealing: 'dry_seal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'NPSI 3/8',
    standards: ['ASME B1.20.3'],
  }),
  anpt: sys({
    id: 'anpt',
    purpose: 'pipe',
    family: 'npt_pipe',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 12716-2011',
    markingExample: 'ANPT 3/8',
    standards: ['ASME B1.20.1'],
  }),

  // —— 管 / BSP ——
  bspp_g: sys({
    id: 'bspp_g',
    purpose: 'pipe',
    family: 'bsp_pipe',
    implemented: true,
    catalog: { system: 'g', subTab: 'g' },
    angle: 55,
    angleLabel: '55°',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 7307-2001',
    markingExample: 'G 3/4A',
    standards: ['ISO 228-1'],
    diagramAngle: 55,
  }),
  bspt_r: sys({
    id: 'bspt_r',
    purpose: 'pipe',
    family: 'bsp_pipe',
    implemented: true,
    catalog: { system: 'r', subTab: 'r' },
    angle: 55,
    angleLabel: '55°',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 7306-2000',
    markingExample: 'R 3/4',
    standards: ['ISO 7-1'],
    diagramAngle: 55,
  }),
  bspt_rc: sys({
    id: 'bspt_rc',
    purpose: 'pipe',
    family: 'bsp_pipe',
    angle: 55,
    angleLabel: '55°',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 7306-2000',
    markingExample: 'Rc 3/4',
    standards: ['ISO 7-1'],
    diagramAngle: 55,
  }),
  bspt_rp: sys({
    id: 'bspt_rp',
    purpose: 'pipe',
    family: 'bsp_pipe',
    angle: 55,
    angleLabel: '55°',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 7306-2000',
    markingExample: 'Rp 3/4',
    standards: ['ISO 7-1'],
    diagramAngle: 55,
  }),
  bspt_r12: sys({
    id: 'bspt_r12',
    purpose: 'pipe',
    family: 'bsp_pipe',
    angle: 55,
    angleLabel: '55°',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GB/T 7306-2000',
    markingExample: 'R1 3/4',
    standards: ['ISO 7-1'],
    diagramAngle: 55,
  }),

  // —— 管 / 日标 ——
  pt_jis: sys({
    id: 'pt_jis',
    purpose: 'pipe',
    family: 'jis_pipe',
    angle: 55,
    angleLabel: '55°',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'JIS B 0203',
    markingExample: 'PT 3/4',
    standards: ['JIS B 0203'],
    diagramAngle: 55,
  }),
  pf_jis: sys({
    id: 'pf_jis',
    purpose: 'pipe',
    family: 'jis_pipe',
    angle: 55,
    angleLabel: '55°',
    sealing: 'gasket',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'JIS B 0202',
    markingExample: 'PF 3/4',
    standards: ['JIS B 0202'],
    diagramAngle: 55,
  }),

  // —— 传动 ——
  tr: sys({
    id: 'tr',
    purpose: 'power',
    family: 'trap_power',
    implemented: true,
    catalog: { system: 'tr', subTab: 'tr' },
    profile: 'trapezoidal',
    angle: 30,
    angleLabel: '30°',
    starts: ['single', 'multi'],
    pitchNotation: 'P_mm',
    gbStandard: 'GB/T 5796-2005',
    markingExample: 'Tr40×7',
    standards: ['ISO 2901', 'ISO 2902', 'ISO 2903', 'ISO 2904'],
    diagramAngle: 30,
  }),
  acme: sys({
    id: 'acme',
    purpose: 'power',
    family: 'trap_power',
    implemented: true,
    catalog: { system: 'acme', subTab: 'acme' },
    profile: 'trapezoidal',
    angle: 29,
    angleLabel: '29°',
    starts: ['single', 'multi'],
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: '1-3/4-4ACME',
    standards: ['ASME B1.5', 'ASME B1.8'],
    diagramAngle: 29,
  }),
  stub_acme: sys({
    id: 'stub_acme',
    purpose: 'power',
    family: 'trap_power',
    profile: 'trapezoidal',
    angle: 29,
    angleLabel: '29°',
    starts: ['single', 'multi'],
    unit: 'in',
    pitchNotation: 'TPI',
    markingExample: '1-3/4-4StubACME',
    standards: ['ASME B1.8'],
    diagramAngle: 29,
  }),
  tr_multi: sys({
    id: 'tr_multi',
    purpose: 'power',
    family: 'trap_power',
    profile: 'trapezoidal',
    angle: 30,
    angleLabel: '30°',
    starts: ['multi'],
    pitchNotation: 'P_mm',
    gbStandard: 'GB/T 5796-2005',
    markingExample: 'Tr40×14(P7)LH',
    standards: ['ISO 2901'],
    diagramAngle: 30,
  }),
  square: sys({
    id: 'square',
    purpose: 'power',
    family: 'other_power',
    profile: 'square',
    angle: null,
    angleLabel: null,
    starts: ['single', 'multi'],
    unit: 'mm_in',
    pitchNotation: 'P_mm',
    diagramAngle: 90,
  }),
  buttress: sys({
    id: 'buttress',
    purpose: 'power',
    family: 'other_power',
    profile: 'buttress',
    angle: null,
    angleLabel: '3°/30°',
    starts: ['single', 'multi'],
    gbStandard: 'GB/T 13576-2008',
    markingExample: 'B40×7',
    standards: ['ISO 13576'],
    diagramAngle: 45,
  }),
  buttress_din513: sys({
    id: 'buttress_din513',
    purpose: 'power',
    family: 'other_power',
    profile: 'buttress',
    angle: 30,
    angleLabel: '30°',
    starts: ['single', 'multi'],
    gbStandard: 'GB/T 13576-2008',
    standards: ['DIN 513'],
    diagramAngle: 30,
  }),
  module_din5480: sys({
    id: 'module_din5480',
    purpose: 'power',
    family: 'other_power',
    angle: null,
    angleLabel: null,
    standards: ['DIN 5480'],
  }),
  ball_screw: sys({
    id: 'ball_screw',
    purpose: 'power',
    family: 'other_power',
    profile: 'ball_screw',
    angle: null,
    angleLabel: null,
    starts: ['single', 'multi'],
    pitchNotation: 'lead_mm',
    gbStandard: 'GB/T 17587.3-2017',
    standards: ['ISO 3408-3'],
  }),

  // —— 特殊 ——
  rd: sys({
    id: 'rd',
    purpose: 'special',
    family: 'round_special',
    profile: 'round',
    angle: 30,
    angleLabel: '30°',
    hand: ['RH'],
    pitchNotation: 'TPI',
    markingExample: 'Rd40×1/6',
    standards: ['DIN 405'],
    diagramAngle: 30,
  }),
  knuckle: sys({
    id: 'knuckle',
    purpose: 'special',
    family: 'round_special',
    profile: 'round',
    angle: 30,
    angleLabel: '30°',
    hand: ['RH'],
    pitchNotation: 'TPI',
    markingExample: 'Rd20×1/8',
    standards: ['DIN 405'],
    diagramAngle: 30,
  }),
  arc_round: sys({
    id: 'arc_round',
    purpose: 'special',
    family: 'round_special',
    profile: 'round',
    angle: 30,
    angleLabel: '30°',
    hand: ['RH'],
    markingExample: 'Rd40×7',
    standards: ['DIN 20400'],
    diagramAngle: 30,
  }),
  edison: sys({
    id: 'edison',
    purpose: 'special',
    family: 'instrument_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    markingExample: 'E27',
    standards: ['DIN 40400'],
  }),
  bottle: sys({
    id: 'bottle',
    purpose: 'special',
    family: 'instrument_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    markingExample: 'PCO 28',
    standards: ['DIN 168-1'],
  }),
  microscope: sys({
    id: 'microscope',
    purpose: 'special',
    family: 'instrument_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    standards: ['DIN 40400'],
  }),
  optical: sys({
    id: 'optical',
    purpose: 'special',
    family: 'instrument_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    standards: ['DIN 40400'],
  }),
  rms_objective: sys({
    id: 'rms_objective',
    purpose: 'special',
    family: 'instrument_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    markingExample: 'RMS',
    standards: ['DIN 40400'],
  }),
  self_tap_st: sys({
    id: 'self_tap_st',
    purpose: 'special',
    family: 'self_tap_special',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    gbStandard: 'GB/T 5280-2002',
    markingExample: 'ST4.2',
    standards: ['ISO 1478'],
  }),
  self_tap_lock: sys({
    id: 'self_tap_lock',
    purpose: 'special',
    family: 'self_tap_special',
    hand: ['RH'],
    gbStandard: 'GB/T 6560-2014',
    standards: ['ISO 7049'],
  }),
  heli_coil: sys({
    id: 'heli_coil',
    purpose: 'special',
    family: 'self_tap_special',
    hand: ['RH'],
    gbStandard: 'GB/T 24425-2009',
    standards: ['DIN 8140'],
  }),
  gas_cylinder: sys({
    id: 'gas_cylinder',
    purpose: 'special',
    family: 'gas_cylinder_special',
    angle: 55,
    angleLabel: '55°',
    hand: ['RH'],
    gbStandard: 'GB/T 8335-2011',
    markingExample: 'PZ27.8',
    standards: ['ISO 6406'],
    diagramAngle: 55,
  }),
  gas_cylinder_taper: sys({
    id: 'gas_cylinder_taper',
    purpose: 'special',
    family: 'gas_cylinder_special',
    angle: 55,
    angleLabel: '55°',
    parentShape: 'conical',
    taper: 'taper',
    sealing: 'taper_metal',
    hand: ['RH'],
    gbStandard: 'GB/T 8335-2011',
    standards: ['ISO 6406'],
    diagramAngle: 55,
  }),

  // —— 石油 ——
  api_stc: sys({
    id: 'api_stc',
    purpose: 'oil',
    family: 'api_round',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '5-1/2 STC',
    standards: ['API 5B'],
  }),
  api_ltc: sys({
    id: 'api_ltc',
    purpose: 'oil',
    family: 'api_round',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '5-1/2 LTC',
    standards: ['API 5B'],
  }),
  api_nue: sys({
    id: 'api_nue',
    purpose: 'oil',
    family: 'api_round',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '2-3/8 NUE',
    standards: ['API 5B'],
  }),
  api_eue: sys({
    id: 'api_eue',
    purpose: 'oil',
    family: 'api_round',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '2-3/8 EUE',
    standards: ['API 5B'],
  }),
  api_btc: sys({
    id: 'api_btc',
    purpose: 'oil',
    family: 'api_trap',
    profile: 'trapezoidal',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '5-1/2 BTC',
    standards: ['API 5B'],
  }),
  api_xc: sys({
    id: 'api_xc',
    purpose: 'oil',
    family: 'api_trap',
    profile: 'trapezoidal',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: '5-1/2 XC',
    standards: ['API 5B'],
  }),
  api_premium: sys({
    id: 'api_premium',
    purpose: 'oil',
    family: 'api_special',
    angle: null,
    angleLabel: null,
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'SY/T 6194',
    markingExample: null,
    standards: ['API 5B'],
  }),

  // —— 航空航天（与紧固类同名体系在此作交叉导航条目） ——
  aero_unj: sys({
    id: 'aero_unj',
    purpose: 'aerospace',
    family: 'aero_strength',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.1-1982',
    markingExample: '1/4-28UNJF',
    standards: ['ASME B1.15'],
  }),
  aero_mj: sys({
    id: 'aero_mj',
    purpose: 'aerospace',
    family: 'aero_strength',
    angleLabel: '60°圆弧牙底',
    gbStandard: 'GJB 3.1-1982',
    markingExample: 'MJ6×1',
    standards: ['ISO 5855'],
  }),
  aero_unjf: sys({
    id: 'aero_unjf',
    purpose: 'aerospace',
    family: 'aero_strength',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.2-1982',
    markingExample: '1/4-28UNJF',
    standards: ['ASME B1.15'],
  }),
  aero_unjc: sys({
    id: 'aero_unjc',
    purpose: 'aerospace',
    family: 'aero_strength',
    angleLabel: '60°圆弧牙底',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'GJB 3.3-1982',
    markingExample: '1/4-28UNJC',
    standards: ['ASME B1.15'],
  }),
  aero_anpt: sys({
    id: 'aero_anpt',
    purpose: 'aerospace',
    family: 'aero_pipe',
    parentShape: 'conical',
    taper: 'taper',
    taperRatio: '1:16',
    sealing: 'taper_metal',
    hand: ['RH'],
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'HB 5800',
    markingExample: 'ANPT 3/8',
    standards: ['ASME B1.20.1'],
  }),
  nas: sys({
    id: 'nas',
    purpose: 'aerospace',
    family: 'aero_std',
    unit: 'in',
    pitchNotation: 'TPI',
    gbStandard: 'NAS 标准',
    markingExample: 'NAS-',
    standards: ['NAS'],
  }),

  // —— 行业专用 ——
  rebar_straight: sys({
    id: 'rebar_straight',
    purpose: 'industry',
    family: 'building_industry',
    hand: ['RH'],
    gbStandard: 'JG/T 163-2013',
    standards: ['ISO 15835'],
  }),
  rebar_taper: sys({
    id: 'rebar_taper',
    purpose: 'industry',
    family: 'building_industry',
    parentShape: 'conical',
    taper: 'taper',
    hand: ['RH'],
    gbStandard: 'JG/T 163-2013',
    standards: ['ISO 15835'],
  }),
  rebar_swage: sys({
    id: 'rebar_swage',
    purpose: 'industry',
    family: 'building_industry',
    hand: ['RH'],
    gbStandard: 'JG/T 163-2013',
    standards: ['ISO 15835'],
  }),
  drill_rod_r: sys({
    id: 'drill_rod_r',
    purpose: 'industry',
    family: 'mining_industry',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    gbStandard: '行业标准',
    markingExample: 'R32',
    standards: ['ISO 10208'],
  }),
  drill_rod_t: sys({
    id: 'drill_rod_t',
    purpose: 'industry',
    family: 'mining_industry',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
    gbStandard: '行业标准',
    markingExample: 'T38',
    standards: ['ISO 10208'],
  }),
  bicycle: sys({
    id: 'bicycle',
    purpose: 'industry',
    family: 'consumer_industry',
    hand: ['RH'],
    gbStandard: 'GB/T 3565-2022',
    standards: ['ISO 4210'],
  }),
  watch: sys({
    id: 'watch',
    purpose: 'industry',
    family: 'consumer_industry',
    angle: null,
    angleLabel: null,
    hand: ['RH'],
  }),
}

/** @param {ThreadPurposeId} purposeId */
export function getSystemsForPurpose(purposeId) {
  return (PURPOSE_SYSTEM_IDS[purposeId] ?? [])
    .map((id) => THREAD_SYSTEM_REGISTRY[id])
    .filter(Boolean)
}

/** @param {string} systemId */
export function getThreadSystemDef(systemId) {
  return THREAD_SYSTEM_REGISTRY[systemId] ?? null
}

/** @returns {ThreadSystemDef[]} */
export function listThreadSystemOverviewRows() {
  /** @type {ThreadSystemDef[]} */
  const rows = []
  for (const purpose of THREAD_PURPOSE_ORDER) {
    for (const id of PURPOSE_SYSTEM_IDS[purpose]) {
      const def = THREAD_SYSTEM_REGISTRY[id]
      if (def) rows.push(def)
    }
  }
  return rows
}

/** @param {string} catalogSystem @param {string} [subSeries] */
export function resolveTaxonomyFromCatalog(catalogSystem, subSeries) {
  if (catalogSystem === 'metric') {
    return 'metric_coarse'
  }
  const map = {
    unc: 'unc',
    unf: 'unf',
    unef: 'unef',
    uns: 'uns',
    tr: 'tr',
    acme: 'acme',
    npt: 'npt',
    nptf: 'nptf',
    g: 'bspp_g',
    r: 'bspt_r',
  }
  return map[catalogSystem] ?? null
}

/** 无尺寸表体系的已收录替代选型（catalog system id） */
export const REFERENCE_CATALOG_ALTERNATIVES = {
  metric_extra_fine: ['metric'],
  metric_small_s: ['metric'],
  mj: ['metric'],
  uns: ['unc', 'unf', 'unef'],
  un: ['unc', 'unf'],
  unj: ['unc', 'unf'],
  unjc: ['unc'],
  unjf: ['unf'],
  whitworth: ['metric', 'unc', 'unf'],
  bsw: ['metric', 'unc'],
  bsf: ['metric', 'unf'],
  ba: ['metric'],
  v_sharp: ['metric', 'unc'],
  nps: ['npt', 'g'],
  npsm: ['npt', 'g'],
  npsl: ['npt', 'g'],
  npsh: ['npt', 'g'],
  npsc: ['npt', 'g'],
  nptr: ['npt'],
  nh: ['npt'],
  npsf: ['nptf'],
  npsi: ['nptf'],
  anpt: ['npt'],
  bspt_rc: ['r'],
  bspt_rp: ['r', 'g'],
  bspt_r12: ['r'],
  pt_jis: ['r'],
  pf_jis: ['g'],
  stub_acme: ['acme'],
  tr_multi: ['tr'],
  square: ['tr', 'acme'],
  buttress: ['tr', 'acme'],
  buttress_din513: ['tr', 'acme'],
  module_din5480: ['tr'],
  ball_screw: ['tr'],
  rd: [],
  knuckle: [],
  arc_round: [],
  edison: [],
  bottle: [],
  microscope: [],
  optical: [],
  rms_objective: [],
  self_tap_st: ['metric'],
  self_tap_lock: ['metric'],
  heli_coil: ['metric'],
  gas_cylinder: [],
  gas_cylinder_taper: [],
  api_stc: [],
  api_ltc: [],
  api_nue: [],
  api_eue: [],
  api_btc: [],
  api_xc: [],
  api_premium: [],
  aero_unj: ['unc', 'unf'],
  aero_mj: ['metric'],
  aero_unjf: ['unf'],
  aero_unjc: ['unc'],
  aero_anpt: ['npt'],
  nas: ['unc', 'unf'],
  rebar_straight: ['metric'],
  rebar_taper: ['metric'],
  rebar_swage: ['metric'],
  drill_rod_r: [],
  drill_rod_t: [],
  bicycle: ['metric'],
  watch: ['metric'],
}

/** @param {string} taxonomySystemId */
export function getReferenceCatalogAlternatives(taxonomySystemId) {
  return REFERENCE_CATALOG_ALTERNATIVES[taxonomySystemId] ?? []
}

/** @param {string} catalogSystem @param {string} [subSeries] */
export function catalogAlternativeToQuery(catalogSystem) {
  if (catalogSystem === 'metric') return { system: 'metric', subSeries: 'coarse' }
  return { system: catalogSystem, subSeries: catalogSystem }
}

/** @param {ThreadPurposeId} purposeId */
export function countImplementedInPurpose(purposeId) {
  return getSystemsForPurpose(purposeId).filter((s) => s.implemented).length
}

/** @returns {ThreadSystemDef[]} */
export function getAllRegisteredSystems() {
  return Object.values(THREAD_SYSTEM_REGISTRY)
}

export const PROFILE_ORDER = ['triangular', 'trapezoidal', 'square', 'buttress', 'round', 'ball_screw']
